### ISSUE TITLE
Function or variable 'chebpts' is not recognized

### ISSUE THREAD

**Issue by hanjinli2023** [yzhao334/Efficient-Trajectory-Optimization-for-Robot-Motion-Planning--Examples#1]
Function or variable 'chebpts' is not recognized
The function or variable 'chebpts' is not recognized, your program is missing the chebpts function

**Comment by yzhao334** [comment]
You need to install chebfun for that function. Please check http://www.chebfun.org for more information.

Also, please make sure you installed CasADi. Both chebfun and CasADi are dependencies of this repo.

**Comment by hanjinli2023** [comment]
hank you for your help，The problem has been solved at your prompt

**Comment by hanjinli2023** [comment]
thank you for your help，The problem has been solved at your prompt
